### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by feldrim**

### CODE REVIEW

**Comment by feldrim** [comment]
Closing because of conflicts

**Comment by johnstaveley** [comment]
Hello feldrin, thanks for the submission. I had a big project this year which used security essentials as a base, it got pen tested and improved a lot. So the branch you were working from was quite old. However I am not expecting any major updates soon so please feel free to contribute! Thanks again, John

**Comment by feldrim** [comment]
Is it possible to see your new project soon on Github?

**Comment by johnstaveley** [comment]
Everything I am going to merge in is already there.

**Comment by feldrim** [comment]
Sorry, my mistake. I've misread your message. Thanks.

**Pull request closed without merging**
